# Generated by Django 4.2.3 on 2023-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("theatre", "0002_initial")]

    operations = [
        migrations.AddField(
            model_name="theatrehall",
            name="seats_in_row",
            field=models.IntegerField(default=10),
            preserve_default=False,
        )
    ]
